### ISSUE TITLE
Fix hardhat-cannon compatibility with hardhat >=2.16.0

### ISSUE THREAD

**Issue by noahlitvin** [usecannon/cannon#351]

**Comment by FuzzB0t** [comment]
current version of hardhat cannon is not compatible with hardhat >= 2.16.0 https://github.com/NomicFoundation/hardhat/releases/tag/hardhat%402.16.0
➜ yarn test
An unexpected error occurred:

TypeError: this._wrapped.on is not a function
    at CannonWrapperProvider.on (./synthetix-v3/node_modules/hardhat/src/internal/util/event-emitter.ts:25:19)
    at BackwardsCompatibilityProviderAdapter.on (./synthetix-v3/node_modules/hardhat/src/internal/util/event-emitter.ts:25:19)
    at createProviderProxy (./synthetix-v3/node_modules/@nomiclabs/hardhat-ethers/src/internal/provider-proxy.ts:25:19)
    at augmentProvider (./synthetix-v3/node_modules/hardhat-cannon/src/internal/augment-provider.ts:50:46)
    at ./synthetix-v3/node_modules/hardhat-cannon/src/index.ts:36:18
    at ./synthetix-v3/node_modules/hardhat/src/internal/core/runtime-environment.ts:119:48
    at Array.forEach (<anonymous>)
    at new Environment (./synthetix-v3/node_modules/hardhat/src/internal/core/runtime-environment.ts:119:26)
    at main (./synthetix-v3/node_modules/hardhat/src/internal/cli/cli.ts:265:17)


Something in Event emitter makes it fail when calling this (it expects to see this._wrapped but in our case it is undefined)
extendEnvironment((env: HardhatRuntimeEnvironment) => {
  augmentProvider(env); // <-- HERE
});


hardhat 2.16.1 fixes issues with node 18.
and hardhat 2.17.1 sorts our problems with node 20.

Quite important to upgrade
